# Generated by Django 5.2.9 on 2025-12-08 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hotel_rooms',
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.hotelrooms')),
            ],
            options={
                'db_table': 'reservations',
                'ordering': ['check_in_date'],
                'indexes': [models.Index(fields=['room', 'check_in_date'], name='reservation_room_id_26bf11_idx')],
            },
        ),
    ]
